'use strict';

/**
 * Pure cross-agent handoff digest builder (v1.4 — "이어받기").
 *
 * The outgoing coding agent (Claude Code or Codex) already writes a full
 * transcript to disk. When a session hits a limit and the work moves to the
 * other agent, `buildHandoffDigest` turns that transcript into a short, fixed
 * shape Markdown brief — recent requests, files touched, commands run, where the
 * agent left off, open checklist — so the incoming agent can pick the thread up
 * without the work being re-explained.
 *
 * Same discipline as shared/guidelines.js and shared/codexSessions.js: no fs, no
 * vscode, no network, NO LLM call. The extension reads the file; this module only
 * extracts structure. Deterministic given the same input (the sanity test pins it
 * against a fixture). A malformed record is skipped, never thrown on.
 *
 * `entries` may be raw JSONL lines (strings) or already-parsed objects — the
 * extension passes raw lines so a single bad line can be tolerated here rather
 * than aborting a JSON.parse loop upstream.
 */

const HEAD = {
  goal: '## Goal / recent requests',
  files: '## Files touched',
  commands: '## Commands run',
  left: '## Where we left off',
  open: '## Open items',
};

const SRC_LABEL = { claude: 'Claude Code', codex: 'Codex' };

const MAX_TURN_CHARS = 500;
const MAX_CMD_CHARS = 120;
const MAX_CMDS = 30;
const MAX_LEFT_CHARS = 600;
const MAX_OPEN_ITEMS = 12;
const MAX_OPEN_BODY = 160;

function asRecord(entry) {
  if (entry && typeof entry === 'object') return entry;
  if (typeof entry === 'string') {
    const s = entry.trim();
    if (!s) return null;
    try {
      return JSON.parse(s);
    } catch (e) {
      return null;
    }
  }
  return null;
}

function collapse(s) {
  return String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
}

function clip(s, n) {
  s = String(s == null ? '' : s).trim();
  if (s.length <= n) return s;
  return s.slice(0, n - 1).replace(/\s+$/, '') + '…';
}

// A "user" turn that is really tooling / injected context, not a human request.
function looksLikeMeta(text) {
  const t = String(text || '').trim();
  if (!t) return true;
  return (
    /^<(command-name|command-message|command-args|local-command-stdout|local-command-stderr|user-prompt-submit-hook)/i.test(t) ||
    /^<(environment_context|user_instructions|system-reminder|editor_context|ide_[a-z_]+)\b/i.test(t) ||
    /^\[Request interrupted/i.test(t) ||
    /^Caveat: The messages below were generated by the user while running/i.test(t)
  );
}

function noteTimestamp(rec, acc) {
  const ts =
    rec.timestamp ||
    rec.ts ||
    (rec.payload && rec.payload.timestamp) ||
    (rec.message && rec.message.timestamp) ||
    '';
  const s = String(ts || '');
  // ISO 8601 strings sort lexicographically = chronologically; good enough for a
  // deterministic "generated at" without reaching for Date.now().
  if (s && s > acc.latestTs) acc.latestTs = s;
}

function pushTurn(acc, text) {
  const t = collapse(text);
  if (!t || looksLikeMeta(t)) return;
  acc.userTurns.push(clip(t, MAX_TURN_CHARS));
}

function addFile(acc, p, mode) {
  const norm = collapse(String(p)).replace(/\\/g, '/');
  if (!norm) return;
  if (acc.fileKeys.has(norm)) return;
  acc.fileKeys.add(norm);
  acc.files.push({ path: norm, mode: mode || 'modified' });
}

function addCommand(acc, cmd) {
  let c = collapse(cmd).replace(/^(?:bash|sh|zsh)\s+-l?c\s+/, '').trim();
  if ((c.startsWith('"') && c.endsWith('"')) || (c.startsWith("'") && c.endsWith("'"))) {
    c = c.slice(1, -1).trim();
  }
  if (!c) return;
  acc.commands.push(clip(c, MAX_CMD_CHARS));
}

function dedupeTail(list, max) {
  const seen = new Set();
  const rev = [];
  for (let i = list.length - 1; i >= 0 && rev.length < max; i--) {
    const v = list[i];
    if (seen.has(v)) continue;
    seen.add(v);
    rev.push(v);
  }
  return rev.reverse();
}

// Best-effort: checkbox lines anywhere, plus bullet/numbered lines that sit under
// a "next steps" / "todo" / "remaining" heading in the last few assistant turns.
function extractOpenItems(texts) {
  const items = [];
  const seen = new Set();
  const add = (checked, body) => {
    body = collapse(body);
    if (!body || seen.has(body)) return;
    seen.add(body);
    items.push('- [' + (checked ? 'x' : ' ') + '] ' + clip(body, MAX_OPEN_BODY));
  };
  for (const block of texts) {
    let inList = false;
    for (const rawLine of String(block || '').split('\n')) {
      const line = rawLine.trim();
      if (!line) {
        inList = false;
        continue;
      }
      const cb = line.match(/^[-*+]\s+\[([ xX])\]\s+(.+)$/);
      if (cb) {
        add(/[xX]/.test(cb[1]), cb[2]);
        if (items.length >= MAX_OPEN_ITEMS) return items;
        continue;
      }
      if (
        /^(?:#{1,6}\s+|\*\*\s*)?(next steps?|to-?do|remaining|open items?|still (?:to do|needed|need to))\b/i.test(line)
      ) {
        inList = true;
        continue;
      }
      const li = line.match(/^(?:[-*+]|\d+[.)])\s+(.+)$/);
      if (li && inList) {
        add(false, li[1]);
        if (items.length >= MAX_OPEN_ITEMS) return items;
      }
    }
  }
  return items;
}

// ---- Claude Code transcript ------------------------------------------------
function scanClaude(rec, acc) {
  const type = rec.type;
  const msg = rec.message && typeof rec.message === 'object' ? rec.message : {};
  const role = type === 'user' || type === 'assistant' ? type : msg.role;
  const content = msg.content;

  if (role === 'user') {
    if (Array.isArray(content)) {
      if (content.some((b) => b && b.type === 'tool_result')) return; // tool output, not a request
      const text = content
        .filter((b) => b && (b.type === 'text' || typeof b === 'string'))
        .map((b) => (typeof b === 'string' ? b : b.text || ''))
        .join('\n');
      pushTurn(acc, text);
    } else if (typeof content === 'string') {
      pushTurn(acc, content);
    }
    return;
  }

  if (role === 'assistant') {
    if (typeof content === 'string') {
      if (content.trim()) acc.assistantTexts.push(content.trim());
      return;
    }
    if (!Array.isArray(content)) return;
    const textParts = [];
    for (const b of content) {
      if (!b || typeof b !== 'object') continue;
      if (b.type === 'text' && b.text) textParts.push(String(b.text).trim());
      else if (b.type === 'tool_use') recordClaudeTool(b, acc);
    }
    if (textParts.length) acc.assistantTexts.push(textParts.join('\n\n').trim());
  }
}

function recordClaudeTool(b, acc) {
  const name = String(b.name || '');
  const input = b.input && typeof b.input === 'object' ? b.input : {};
  if (name === 'Bash') {
    if (input.command) addCommand(acc, input.command);
    return;
  }
  if (name === 'Write') {
    if (input.file_path) addFile(acc, input.file_path, 'created');
    return;
  }
  if (name === 'Edit' || name === 'MultiEdit') {
    if (input.file_path) addFile(acc, input.file_path, 'modified');
    return;
  }
  if (name === 'NotebookEdit') {
    const p = input.notebook_path || input.file_path;
    if (p) addFile(acc, p, 'modified');
  }
}

// ---- Codex rollout transcript --------------------------------------------
function scanCodex(rec, acc) {
  const outer = rec.type;
  const p = rec.payload && typeof rec.payload === 'object' ? rec.payload : rec;
  const ptype = p.type || outer;

  if (ptype === 'message') {
    const role = p.role;
    if (role !== 'user' && role !== 'assistant') return; // developer / system excluded
    const text = codexText(p.content);
    if (role === 'user') pushTurn(acc, text);
    else if (text && text.trim()) acc.assistantTexts.push(text.trim());
    return;
  }

  if (
    ptype === 'function_call' ||
    ptype === 'local_shell_call' ||
    ptype === 'exec_command_begin' ||
    ptype === 'shell_call'
  ) {
    const cmd = codexCommand(p);
    if (cmd) addCommand(acc, cmd);
    return;
  }

  if (ptype === 'patch_apply_begin' || ptype === 'apply_patch' || ptype === 'apply_patch_approval_request') {
    const changes = p.changes || (p.input && p.input.changes) || (p.args && p.args.changes);
    if (changes && typeof changes === 'object') {
      for (const fp of Object.keys(changes)) {
        const c = changes[fp] && typeof changes[fp] === 'object' ? changes[fp] : {};
        const mode = c.add ? 'created' : c.delete || c.remove ? 'deleted' : 'modified';
        addFile(acc, fp, mode);
      }
    }
  }
}

function codexText(content) {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  return content
    .filter((b) => b && typeof b === 'object' && typeof b.text === 'string')
    .map((b) => b.text)
    .join('\n');
}

function codexCommand(p) {
  if (Array.isArray(p.command)) return p.command.join(' ');
  if (typeof p.command === 'string') return p.command;
  if (typeof p.arguments === 'string') {
    try {
      const a = JSON.parse(p.arguments);
      if (a && Array.isArray(a.command)) return a.command.join(' ');
      if (a && typeof a.command === 'string') return a.command;
    } catch (e) {
      /* ignore */
    }
  }
  if (p.arguments && typeof p.arguments === 'object' && Array.isArray(p.arguments.command)) {
    return p.arguments.command.join(' ');
  }
  return '';
}

/**
 * @param {{source?:'claude'|'codex', entries?:Array, maxTurns?:number, now?:string}} opts
 * @returns {string} deterministic Markdown
 */
function buildHandoffDigest(opts) {
  opts = opts || {};
  const source = opts.source === 'codex' ? 'codex' : 'claude';
  const label = SRC_LABEL[source];
  const maxTurns =
    Number.isFinite(opts.maxTurns) && opts.maxTurns > 0 ? Math.floor(opts.maxTurns) : 20;
  const entries = Array.isArray(opts.entries) ? opts.entries : [];

  const acc = {
    userTurns: [],
    files: [],
    fileKeys: new Set(),
    commands: [],
    assistantTexts: [],
    latestTs: '',
  };

  for (const entry of entries) {
    const rec = asRecord(entry);
    if (!rec || typeof rec !== 'object') continue;
    try {
      noteTimestamp(rec, acc);
      if (source === 'codex') scanCodex(rec, acc);
      else scanClaude(rec, acc);
    } catch (e) {
      /* one bad record must never abort the digest */
    }
  }

  const turns = acc.userTurns.slice(-maxTurns);
  const commands = dedupeTail(acc.commands, MAX_CMDS);
  const left = clip(
    acc.assistantTexts.length ? acc.assistantTexts[acc.assistantTexts.length - 1] : '',
    MAX_LEFT_CHARS
  );
  const open = extractOpenItems(acc.assistantTexts.slice(-3));
  const generatedAt = String(opts.now || acc.latestTs || '').trim();

  const out = [];
  out.push('# Handoff — from ' + label);
  out.push('');
  out.push(
    '_generated ' +
      (generatedAt || 'n/a') +
      ' · last ' +
      turns.length +
      ' turn' +
      (turns.length === 1 ? '' : 's') +
      '_'
  );
  out.push('');

  out.push(HEAD.goal);
  if (turns.length) for (const t of turns) out.push('- ' + t);
  else out.push('_(no user turns found in the transcript)_');
  out.push('');

  out.push(HEAD.files);
  if (acc.files.length) for (const f of acc.files) out.push('- `' + f.path + '` — ' + f.mode);
  else out.push('_(none recorded)_');
  out.push('');

  out.push(HEAD.commands);
  if (commands.length) for (const c of commands) out.push('- `' + c + '`');
  else out.push('_(none recorded)_');
  out.push('');

  out.push(HEAD.left);
  out.push(left || '_(the outgoing agent left no closing message)_');
  out.push('');

  out.push(HEAD.open);
  if (open.length) for (const o of open) out.push(o);
  else out.push('_(none captured — restate the next steps before continuing)_');
  out.push('');

  return out.join('\n');
}

module.exports = { buildHandoffDigest, HEADINGS: HEAD };
